name: Install and test

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        backend: ['tensorflow', 'jax', 'torch']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python, Poetry and Dependencies
      uses: packetcoders/action-setup-cache-python-poetry@main
      with:
        python-version: ${{ matrix.python-version }}
        install-args: --with dev --with ${{ matrix.backend }}

    - name: Install geqco
      run: poetry install

    - name: Test
      env:
        KERAS_BACKEND: ${{ matrix.backend }}
      run: |
        poetry run pytest
